package com.administration.account.pojo;

public class CityTest {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column city_test.id
     *
     * @mbg.generated Fri Apr 12 15:23:05 CST 2019
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column city_test.code
     *
     * @mbg.generated Fri Apr 12 15:23:05 CST 2019
     */
    private String code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column city_test.name
     *
     * @mbg.generated Fri Apr 12 15:23:05 CST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column city_test.en_name
     *
     * @mbg.generated Fri Apr 12 15:23:05 CST 2019
     */
    private String enName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column city_test.pid
     *
     * @mbg.generated Fri Apr 12 15:23:05 CST 2019
     */
    private Long pid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column city_test.valid_for_started
     *
     * @mbg.generated Fri Apr 12 15:23:05 CST 2019
     */
    private Byte validForStarted;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column city_test.calling_code
     *
     * @mbg.generated Fri Apr 12 15:23:05 CST 2019
     */
    private String callingCode;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column city_test.id
     *
     * @return the value of city_test.id
     *
     * @mbg.generated Fri Apr 12 15:23:05 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column city_test.id
     *
     * @param id the value for city_test.id
     *
     * @mbg.generated Fri Apr 12 15:23:05 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column city_test.code
     *
     * @return the value of city_test.code
     *
     * @mbg.generated Fri Apr 12 15:23:05 CST 2019
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column city_test.code
     *
     * @param code the value for city_test.code
     *
     * @mbg.generated Fri Apr 12 15:23:05 CST 2019
     */
    public void setCode(String code) {
        this.code = code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column city_test.name
     *
     * @return the value of city_test.name
     *
     * @mbg.generated Fri Apr 12 15:23:05 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column city_test.name
     *
     * @param name the value for city_test.name
     *
     * @mbg.generated Fri Apr 12 15:23:05 CST 2019
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column city_test.en_name
     *
     * @return the value of city_test.en_name
     *
     * @mbg.generated Fri Apr 12 15:23:05 CST 2019
     */
    public String getEnName() {
        return enName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column city_test.en_name
     *
     * @param enName the value for city_test.en_name
     *
     * @mbg.generated Fri Apr 12 15:23:05 CST 2019
     */
    public void setEnName(String enName) {
        this.enName = enName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column city_test.pid
     *
     * @return the value of city_test.pid
     *
     * @mbg.generated Fri Apr 12 15:23:05 CST 2019
     */
    public Long getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column city_test.pid
     *
     * @param pid the value for city_test.pid
     *
     * @mbg.generated Fri Apr 12 15:23:05 CST 2019
     */
    public void setPid(Long pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column city_test.valid_for_started
     *
     * @return the value of city_test.valid_for_started
     *
     * @mbg.generated Fri Apr 12 15:23:05 CST 2019
     */
    public Byte getValidForStarted() {
        return validForStarted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column city_test.valid_for_started
     *
     * @param validForStarted the value for city_test.valid_for_started
     *
     * @mbg.generated Fri Apr 12 15:23:05 CST 2019
     */
    public void setValidForStarted(Byte validForStarted) {
        this.validForStarted = validForStarted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column city_test.calling_code
     *
     * @return the value of city_test.calling_code
     *
     * @mbg.generated Fri Apr 12 15:23:05 CST 2019
     */
    public String getCallingCode() {
        return callingCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column city_test.calling_code
     *
     * @param callingCode the value for city_test.calling_code
     *
     * @mbg.generated Fri Apr 12 15:23:05 CST 2019
     */
    public void setCallingCode(String callingCode) {
        this.callingCode = callingCode;
    }
}