package com.administration.subject.pojo;

import java.util.Date;

public class ApplyLogin {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apply_login.id
     *
     * @mbg.generated Wed Apr 10 10:51:34 CST 2019
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apply_login.serial
     *
     * @mbg.generated Wed Apr 10 10:51:34 CST 2019
     */
    private String serial;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apply_login.account_id
     *
     * @mbg.generated Wed Apr 10 10:51:34 CST 2019
     */
    private Long accountId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apply_login.present_login
     *
     * @mbg.generated Wed Apr 10 10:51:34 CST 2019
     */
    private Long presentLogin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apply_login.login
     *
     * @mbg.generated Wed Apr 10 10:51:34 CST 2019
     */
    private Long login;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apply_login.apply_time
     *
     * @mbg.generated Wed Apr 10 10:51:34 CST 2019
     */
    private Date applyTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apply_login.approve_user
     *
     * @mbg.generated Wed Apr 10 10:51:34 CST 2019
     */
    private Long approveUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apply_login.approve_time
     *
     * @mbg.generated Wed Apr 10 10:51:34 CST 2019
     */
    private Date approveTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apply_login.comment
     *
     * @mbg.generated Wed Apr 10 10:51:34 CST 2019
     */
    private String comment;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apply_login.status
     *
     * @mbg.generated Wed Apr 10 10:51:34 CST 2019
     */
    private Byte status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apply_login.type
     *
     * @mbg.generated Wed Apr 10 10:51:34 CST 2019
     */
    private Byte type;
    
    
    private String total;

    public String getTotal() {
		return total;
	}

	public void setTotal(String total) {
		this.total = total;
	}

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apply_login.id
     *
     * @return the value of apply_login.id
     *
     * @mbg.generated Wed Apr 10 10:51:34 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apply_login.id
     *
     * @param id the value for apply_login.id
     *
     * @mbg.generated Wed Apr 10 10:51:34 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apply_login.serial
     *
     * @return the value of apply_login.serial
     *
     * @mbg.generated Wed Apr 10 10:51:34 CST 2019
     */
    public String getSerial() {
        return serial;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apply_login.serial
     *
     * @param serial the value for apply_login.serial
     *
     * @mbg.generated Wed Apr 10 10:51:34 CST 2019
     */
    public void setSerial(String serial) {
        this.serial = serial;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apply_login.account_id
     *
     * @return the value of apply_login.account_id
     *
     * @mbg.generated Wed Apr 10 10:51:34 CST 2019
     */
    public Long getAccountId() {
        return accountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apply_login.account_id
     *
     * @param accountId the value for apply_login.account_id
     *
     * @mbg.generated Wed Apr 10 10:51:34 CST 2019
     */
    public void setAccountId(Long accountId) {
        this.accountId = accountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apply_login.present_login
     *
     * @return the value of apply_login.present_login
     *
     * @mbg.generated Wed Apr 10 10:51:34 CST 2019
     */
    public Long getPresentLogin() {
        return presentLogin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apply_login.present_login
     *
     * @param presentLogin the value for apply_login.present_login
     *
     * @mbg.generated Wed Apr 10 10:51:34 CST 2019
     */
    public void setPresentLogin(Long presentLogin) {
        this.presentLogin = presentLogin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apply_login.login
     *
     * @return the value of apply_login.login
     *
     * @mbg.generated Wed Apr 10 10:51:34 CST 2019
     */
    public Long getLogin() {
        return login;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apply_login.login
     *
     * @param login the value for apply_login.login
     *
     * @mbg.generated Wed Apr 10 10:51:34 CST 2019
     */
    public void setLogin(Long login) {
        this.login = login;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apply_login.apply_time
     *
     * @return the value of apply_login.apply_time
     *
     * @mbg.generated Wed Apr 10 10:51:34 CST 2019
     */
    public Date getApplyTime() {
        return applyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apply_login.apply_time
     *
     * @param applyTime the value for apply_login.apply_time
     *
     * @mbg.generated Wed Apr 10 10:51:34 CST 2019
     */
    public void setApplyTime(Date applyTime) {
        this.applyTime = applyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apply_login.approve_user
     *
     * @return the value of apply_login.approve_user
     *
     * @mbg.generated Wed Apr 10 10:51:34 CST 2019
     */
    public Long getApproveUser() {
        return approveUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apply_login.approve_user
     *
     * @param approveUser the value for apply_login.approve_user
     *
     * @mbg.generated Wed Apr 10 10:51:34 CST 2019
     */
    public void setApproveUser(Long approveUser) {
        this.approveUser = approveUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apply_login.approve_time
     *
     * @return the value of apply_login.approve_time
     *
     * @mbg.generated Wed Apr 10 10:51:34 CST 2019
     */
    public Date getApproveTime() {
        return approveTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apply_login.approve_time
     *
     * @param approveTime the value for apply_login.approve_time
     *
     * @mbg.generated Wed Apr 10 10:51:34 CST 2019
     */
    public void setApproveTime(Date approveTime) {
        this.approveTime = approveTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apply_login.comment
     *
     * @return the value of apply_login.comment
     *
     * @mbg.generated Wed Apr 10 10:51:34 CST 2019
     */
    public String getComment() {
        return comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apply_login.comment
     *
     * @param comment the value for apply_login.comment
     *
     * @mbg.generated Wed Apr 10 10:51:34 CST 2019
     */
    public void setComment(String comment) {
        this.comment = comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apply_login.status
     *
     * @return the value of apply_login.status
     *
     * @mbg.generated Wed Apr 10 10:51:34 CST 2019
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apply_login.status
     *
     * @param status the value for apply_login.status
     *
     * @mbg.generated Wed Apr 10 10:51:34 CST 2019
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apply_login.type
     *
     * @return the value of apply_login.type
     *
     * @mbg.generated Wed Apr 10 10:51:34 CST 2019
     */
    public Byte getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apply_login.type
     *
     * @param type the value for apply_login.type
     *
     * @mbg.generated Wed Apr 10 10:51:34 CST 2019
     */
    public void setType(Byte type) {
        this.type = type;
    }
}