package com.administration.subject.pojo;

import java.math.BigDecimal;
import java.util.Date;

public class ApplyTransfer {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apply_transfer.id
     *
     * @mbg.generated Thu Apr 11 14:26:38 CST 2019
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apply_transfer.serial
     *
     * @mbg.generated Thu Apr 11 14:26:38 CST 2019
     */
    private String serial;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apply_transfer.account_id
     *
     * @mbg.generated Thu Apr 11 14:26:38 CST 2019
     */
    private Long accountId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apply_transfer.from
     *
     * @mbg.generated Thu Apr 11 14:26:38 CST 2019
     */
    private Long from;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apply_transfer.to
     *
     * @mbg.generated Thu Apr 11 14:26:38 CST 2019
     */
    private Long to;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apply_transfer.number
     *
     * @mbg.generated Thu Apr 11 14:26:38 CST 2019
     */
    private BigDecimal number;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apply_transfer.apply_time
     *
     * @mbg.generated Thu Apr 11 14:26:38 CST 2019
     */
    private Date applyTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apply_transfer.approve_user
     *
     * @mbg.generated Thu Apr 11 14:26:38 CST 2019
     */
    private Long approveUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apply_transfer.approve_time
     *
     * @mbg.generated Thu Apr 11 14:26:38 CST 2019
     */
    private Date approveTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apply_transfer.comment
     *
     * @mbg.generated Thu Apr 11 14:26:38 CST 2019
     */
    private String comment;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apply_transfer.status
     *
     * @mbg.generated Thu Apr 11 14:26:38 CST 2019
     */
    private Byte status;
    
    
    private String total;

    public String getTotal() {
		return total;
	}

	public void setTotal(String total) {
		this.total = total;
	}

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apply_transfer.id
     *
     * @return the value of apply_transfer.id
     *
     * @mbg.generated Thu Apr 11 14:26:38 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apply_transfer.id
     *
     * @param id the value for apply_transfer.id
     *
     * @mbg.generated Thu Apr 11 14:26:38 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apply_transfer.serial
     *
     * @return the value of apply_transfer.serial
     *
     * @mbg.generated Thu Apr 11 14:26:38 CST 2019
     */
    public String getSerial() {
        return serial;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apply_transfer.serial
     *
     * @param serial the value for apply_transfer.serial
     *
     * @mbg.generated Thu Apr 11 14:26:38 CST 2019
     */
    public void setSerial(String serial) {
        this.serial = serial;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apply_transfer.account_id
     *
     * @return the value of apply_transfer.account_id
     *
     * @mbg.generated Thu Apr 11 14:26:38 CST 2019
     */
    public Long getAccountId() {
        return accountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apply_transfer.account_id
     *
     * @param accountId the value for apply_transfer.account_id
     *
     * @mbg.generated Thu Apr 11 14:26:38 CST 2019
     */
    public void setAccountId(Long accountId) {
        this.accountId = accountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apply_transfer.from
     *
     * @return the value of apply_transfer.from
     *
     * @mbg.generated Thu Apr 11 14:26:38 CST 2019
     */
    public Long getFrom() {
        return from;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apply_transfer.from
     *
     * @param from the value for apply_transfer.from
     *
     * @mbg.generated Thu Apr 11 14:26:38 CST 2019
     */
    public void setFrom(Long from) {
        this.from = from;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apply_transfer.to
     *
     * @return the value of apply_transfer.to
     *
     * @mbg.generated Thu Apr 11 14:26:38 CST 2019
     */
    public Long getTo() {
        return to;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apply_transfer.to
     *
     * @param to the value for apply_transfer.to
     *
     * @mbg.generated Thu Apr 11 14:26:38 CST 2019
     */
    public void setTo(Long to) {
        this.to = to;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apply_transfer.number
     *
     * @return the value of apply_transfer.number
     *
     * @mbg.generated Thu Apr 11 14:26:38 CST 2019
     */
    public BigDecimal getNumber() {
        return number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apply_transfer.number
     *
     * @param number the value for apply_transfer.number
     *
     * @mbg.generated Thu Apr 11 14:26:38 CST 2019
     */
    public void setNumber(BigDecimal number) {
        this.number = number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apply_transfer.apply_time
     *
     * @return the value of apply_transfer.apply_time
     *
     * @mbg.generated Thu Apr 11 14:26:38 CST 2019
     */
    public Date getApplyTime() {
        return applyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apply_transfer.apply_time
     *
     * @param applyTime the value for apply_transfer.apply_time
     *
     * @mbg.generated Thu Apr 11 14:26:38 CST 2019
     */
    public void setApplyTime(Date applyTime) {
        this.applyTime = applyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apply_transfer.approve_user
     *
     * @return the value of apply_transfer.approve_user
     *
     * @mbg.generated Thu Apr 11 14:26:38 CST 2019
     */
    public Long getApproveUser() {
        return approveUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apply_transfer.approve_user
     *
     * @param approveUser the value for apply_transfer.approve_user
     *
     * @mbg.generated Thu Apr 11 14:26:38 CST 2019
     */
    public void setApproveUser(Long approveUser) {
        this.approveUser = approveUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apply_transfer.approve_time
     *
     * @return the value of apply_transfer.approve_time
     *
     * @mbg.generated Thu Apr 11 14:26:38 CST 2019
     */
    public Date getApproveTime() {
        return approveTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apply_transfer.approve_time
     *
     * @param approveTime the value for apply_transfer.approve_time
     *
     * @mbg.generated Thu Apr 11 14:26:38 CST 2019
     */
    public void setApproveTime(Date approveTime) {
        this.approveTime = approveTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apply_transfer.comment
     *
     * @return the value of apply_transfer.comment
     *
     * @mbg.generated Thu Apr 11 14:26:38 CST 2019
     */
    public String getComment() {
        return comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apply_transfer.comment
     *
     * @param comment the value for apply_transfer.comment
     *
     * @mbg.generated Thu Apr 11 14:26:38 CST 2019
     */
    public void setComment(String comment) {
        this.comment = comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apply_transfer.status
     *
     * @return the value of apply_transfer.status
     *
     * @mbg.generated Thu Apr 11 14:26:38 CST 2019
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apply_transfer.status
     *
     * @param status the value for apply_transfer.status
     *
     * @mbg.generated Thu Apr 11 14:26:38 CST 2019
     */
    public void setStatus(Byte status) {
        this.status = status;
    }
}