package com.administration.subject.pojo;

import java.util.Date;

public class ApplyLeverage {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apply_leverage.id
     *
     * @mbg.generated Wed Apr 10 10:51:34 CST 2019
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apply_leverage.serial
     *
     * @mbg.generated Wed Apr 10 10:51:34 CST 2019
     */
    private String serial;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apply_leverage.account_id
     *
     * @mbg.generated Wed Apr 10 10:51:34 CST 2019
     */
    private Long accountId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apply_leverage.login
     *
     * @mbg.generated Wed Apr 10 10:51:34 CST 2019
     */
    private Long login;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apply_leverage.old_leverage
     *
     * @mbg.generated Wed Apr 10 10:51:34 CST 2019
     */
    private Integer oldLeverage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apply_leverage.new_leverage
     *
     * @mbg.generated Wed Apr 10 10:51:34 CST 2019
     */
    private Integer newLeverage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apply_leverage.status
     *
     * @mbg.generated Wed Apr 10 10:51:34 CST 2019
     */
    private Byte status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apply_leverage.apply_time
     *
     * @mbg.generated Wed Apr 10 10:51:34 CST 2019
     */
    private Date applyTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apply_leverage.approve_user
     *
     * @mbg.generated Wed Apr 10 10:51:34 CST 2019
     */
    private Long approveUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apply_leverage.approve_time
     *
     * @mbg.generated Wed Apr 10 10:51:34 CST 2019
     */
    private Date approveTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apply_leverage.comment
     *
     * @mbg.generated Wed Apr 10 10:51:34 CST 2019
     */
    private String comment;
    
    private String name;
    
    private String total;

    public String getTotal() {
		return total;
	}

	public void setTotal(String total) {
		this.total = total;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apply_leverage.id
     *
     * @return the value of apply_leverage.id
     *
     * @mbg.generated Wed Apr 10 10:51:34 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apply_leverage.id
     *
     * @param id the value for apply_leverage.id
     *
     * @mbg.generated Wed Apr 10 10:51:34 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apply_leverage.serial
     *
     * @return the value of apply_leverage.serial
     *
     * @mbg.generated Wed Apr 10 10:51:34 CST 2019
     */
    public String getSerial() {
        return serial;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apply_leverage.serial
     *
     * @param serial the value for apply_leverage.serial
     *
     * @mbg.generated Wed Apr 10 10:51:34 CST 2019
     */
    public void setSerial(String serial) {
        this.serial = serial;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apply_leverage.account_id
     *
     * @return the value of apply_leverage.account_id
     *
     * @mbg.generated Wed Apr 10 10:51:34 CST 2019
     */
    public Long getAccountId() {
        return accountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apply_leverage.account_id
     *
     * @param accountId the value for apply_leverage.account_id
     *
     * @mbg.generated Wed Apr 10 10:51:34 CST 2019
     */
    public void setAccountId(Long accountId) {
        this.accountId = accountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apply_leverage.login
     *
     * @return the value of apply_leverage.login
     *
     * @mbg.generated Wed Apr 10 10:51:34 CST 2019
     */
    public Long getLogin() {
        return login;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apply_leverage.login
     *
     * @param login the value for apply_leverage.login
     *
     * @mbg.generated Wed Apr 10 10:51:34 CST 2019
     */
    public void setLogin(Long login) {
        this.login = login;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apply_leverage.old_leverage
     *
     * @return the value of apply_leverage.old_leverage
     *
     * @mbg.generated Wed Apr 10 10:51:34 CST 2019
     */
    public Integer getOldLeverage() {
        return oldLeverage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apply_leverage.old_leverage
     *
     * @param oldLeverage the value for apply_leverage.old_leverage
     *
     * @mbg.generated Wed Apr 10 10:51:34 CST 2019
     */
    public void setOldLeverage(Integer oldLeverage) {
        this.oldLeverage = oldLeverage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apply_leverage.new_leverage
     *
     * @return the value of apply_leverage.new_leverage
     *
     * @mbg.generated Wed Apr 10 10:51:34 CST 2019
     */
    public Integer getNewLeverage() {
        return newLeverage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apply_leverage.new_leverage
     *
     * @param newLeverage the value for apply_leverage.new_leverage
     *
     * @mbg.generated Wed Apr 10 10:51:34 CST 2019
     */
    public void setNewLeverage(Integer newLeverage) {
        this.newLeverage = newLeverage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apply_leverage.status
     *
     * @return the value of apply_leverage.status
     *
     * @mbg.generated Wed Apr 10 10:51:34 CST 2019
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apply_leverage.status
     *
     * @param status the value for apply_leverage.status
     *
     * @mbg.generated Wed Apr 10 10:51:34 CST 2019
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apply_leverage.apply_time
     *
     * @return the value of apply_leverage.apply_time
     *
     * @mbg.generated Wed Apr 10 10:51:34 CST 2019
     */
    public Date getApplyTime() {
        return applyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apply_leverage.apply_time
     *
     * @param applyTime the value for apply_leverage.apply_time
     *
     * @mbg.generated Wed Apr 10 10:51:34 CST 2019
     */
    public void setApplyTime(Date applyTime) {
        this.applyTime = applyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apply_leverage.approve_user
     *
     * @return the value of apply_leverage.approve_user
     *
     * @mbg.generated Wed Apr 10 10:51:34 CST 2019
     */
    public Long getApproveUser() {
        return approveUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apply_leverage.approve_user
     *
     * @param approveUser the value for apply_leverage.approve_user
     *
     * @mbg.generated Wed Apr 10 10:51:34 CST 2019
     */
    public void setApproveUser(Long approveUser) {
        this.approveUser = approveUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apply_leverage.approve_time
     *
     * @return the value of apply_leverage.approve_time
     *
     * @mbg.generated Wed Apr 10 10:51:34 CST 2019
     */
    public Date getApproveTime() {
        return approveTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apply_leverage.approve_time
     *
     * @param approveTime the value for apply_leverage.approve_time
     *
     * @mbg.generated Wed Apr 10 10:51:34 CST 2019
     */
    public void setApproveTime(Date approveTime) {
        this.approveTime = approveTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apply_leverage.comment
     *
     * @return the value of apply_leverage.comment
     *
     * @mbg.generated Wed Apr 10 10:51:34 CST 2019
     */
    public String getComment() {
        return comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apply_leverage.comment
     *
     * @param comment the value for apply_leverage.comment
     *
     * @mbg.generated Wed Apr 10 10:51:34 CST 2019
     */
    public void setComment(String comment) {
        this.comment = comment;
    }
}