package com.administration.subject.pojo;

import java.util.Date;

public class CrmUser {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column crm_user.Id
	 * @mbg.generated  Tue Apr 09 15:51:26 CST 2019
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column crm_user.Name
	 * @mbg.generated  Tue Apr 09 15:51:26 CST 2019
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column crm_user.Pwd
	 * @mbg.generated  Tue Apr 09 15:51:26 CST 2019
	 */
	private String pwd;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column crm_user.Role
	 * @mbg.generated  Tue Apr 09 15:51:26 CST 2019
	 */
	private Integer role;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column crm_user.Mobile
	 * @mbg.generated  Tue Apr 09 15:51:26 CST 2019
	 */
	private String mobile;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column crm_user.position
	 * @mbg.generated  Tue Apr 09 15:51:26 CST 2019
	 */
	private String position;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column crm_user.Status
	 * @mbg.generated  Tue Apr 09 15:51:26 CST 2019
	 */
	private Integer status;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column crm_user.Account_addr
	 * @mbg.generated  Tue Apr 09 15:51:26 CST 2019
	 */
	private String accountAddr;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column crm_user.Last_err_time
	 * @mbg.generated  Tue Apr 09 15:51:26 CST 2019
	 */
	private Date lastErrTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column crm_user.Err_number
	 * @mbg.generated  Tue Apr 09 15:51:26 CST 2019
	 */
	private Integer errNumber;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column crm_user.Email
	 * @mbg.generated  Tue Apr 09 15:51:26 CST 2019
	 */
	private String email;
	
	private RoleMgmt roleMgmt;
    
    

    public RoleMgmt getRoleMgmt() {
		return roleMgmt;
	}

	public void setRoleMgmt(RoleMgmt roleMgmt) {
		this.roleMgmt = roleMgmt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column crm_user.Id
	 * @return  the value of crm_user.Id
	 * @mbg.generated  Tue Apr 09 15:51:26 CST 2019
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column crm_user.Id
	 * @param Long  the value for crm_user.Id
	 * @mbg.generated  Tue Apr 09 15:51:26 CST 2019
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column crm_user.Name
	 * @return  the value of crm_user.Name
	 * @mbg.generated  Tue Apr 09 15:51:26 CST 2019
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column crm_user.Name
	 * @param name  the value for crm_user.Name
	 * @mbg.generated  Tue Apr 09 15:51:26 CST 2019
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column crm_user.Pwd
	 * @return  the value of crm_user.Pwd
	 * @mbg.generated  Tue Apr 09 15:51:26 CST 2019
	 */
	public String getPwd() {
		return pwd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column crm_user.Pwd
	 * @param pwd  the value for crm_user.Pwd
	 * @mbg.generated  Tue Apr 09 15:51:26 CST 2019
	 */
	public void setPwd(String pwd) {
		this.pwd = pwd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column crm_user.Role
	 * @return  the value of crm_user.Role
	 * @mbg.generated  Tue Apr 09 15:51:26 CST 2019
	 */
	public Integer getRole() {
		return role;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column crm_user.Role
	 * @param role  the value for crm_user.Role
	 * @mbg.generated  Tue Apr 09 15:51:26 CST 2019
	 */
	public void setRole(Integer role) {
		this.role = role;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column crm_user.Mobile
	 * @return  the value of crm_user.Mobile
	 * @mbg.generated  Tue Apr 09 15:51:26 CST 2019
	 */
	public String getMobile() {
		return mobile;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column crm_user.Mobile
	 * @param mobile  the value for crm_user.Mobile
	 * @mbg.generated  Tue Apr 09 15:51:26 CST 2019
	 */
	public void setMobile(String mobile) {
		this.mobile = mobile;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column crm_user.position
	 * @return  the value of crm_user.position
	 * @mbg.generated  Tue Apr 09 15:51:26 CST 2019
	 */
	public String getPosition() {
		return position;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column crm_user.position
	 * @param position  the value for crm_user.position
	 * @mbg.generated  Tue Apr 09 15:51:26 CST 2019
	 */
	public void setPosition(String position) {
		this.position = position;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column crm_user.Status
	 * @return  the value of crm_user.Status
	 * @mbg.generated  Tue Apr 09 15:51:26 CST 2019
	 */
	public Integer getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column crm_user.Status
	 * @param status  the value for crm_user.Status
	 * @mbg.generated  Tue Apr 09 15:51:26 CST 2019
	 */
	public void setStatus(Integer status) {
		this.status = status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column crm_user.Account_addr
	 * @return  the value of crm_user.Account_addr
	 * @mbg.generated  Tue Apr 09 15:51:26 CST 2019
	 */
	public String getAccountAddr() {
		return accountAddr;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column crm_user.Account_addr
	 * @param accountAddr  the value for crm_user.Account_addr
	 * @mbg.generated  Tue Apr 09 15:51:26 CST 2019
	 */
	public void setAccountAddr(String accountAddr) {
		this.accountAddr = accountAddr;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column crm_user.Last_err_time
	 * @return  the value of crm_user.Last_err_time
	 * @mbg.generated  Tue Apr 09 15:51:26 CST 2019
	 */
	public Date getLastErrTime() {
		return lastErrTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column crm_user.Last_err_time
	 * @param lastErrTime  the value for crm_user.Last_err_time
	 * @mbg.generated  Tue Apr 09 15:51:26 CST 2019
	 */
	public void setLastErrTime(Date lastErrTime) {
		this.lastErrTime = lastErrTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column crm_user.Err_number
	 * @return  the value of crm_user.Err_number
	 * @mbg.generated  Tue Apr 09 15:51:26 CST 2019
	 */
	public Integer getErrNumber() {
		return errNumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column crm_user.Err_number
	 * @param errNumber  the value for crm_user.Err_number
	 * @mbg.generated  Tue Apr 09 15:51:26 CST 2019
	 */
	public void setErrNumber(Integer errNumber) {
		this.errNumber = errNumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column crm_user.Email
	 * @return  the value of crm_user.Email
	 * @mbg.generated  Tue Apr 09 15:51:26 CST 2019
	 */
	public String getEmail() {
		return email;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column crm_user.Email
	 * @param email  the value for crm_user.Email
	 * @mbg.generated  Tue Apr 09 15:51:26 CST 2019
	 */
	public void setEmail(String email) {
		this.email = email;
	}
}