package com.administration.subject.pojo;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class CrmUserExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table crm_user
	 * @mbg.generated  Tue Apr 09 15:51:26 CST 2019
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table crm_user
	 * @mbg.generated  Tue Apr 09 15:51:26 CST 2019
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table crm_user
	 * @mbg.generated  Tue Apr 09 15:51:26 CST 2019
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table crm_user
	 * @mbg.generated  Tue Apr 09 15:51:26 CST 2019
	 */
	public CrmUserExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table crm_user
	 * @mbg.generated  Tue Apr 09 15:51:26 CST 2019
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table crm_user
	 * @mbg.generated  Tue Apr 09 15:51:26 CST 2019
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table crm_user
	 * @mbg.generated  Tue Apr 09 15:51:26 CST 2019
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table crm_user
	 * @mbg.generated  Tue Apr 09 15:51:26 CST 2019
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table crm_user
	 * @mbg.generated  Tue Apr 09 15:51:26 CST 2019
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table crm_user
	 * @mbg.generated  Tue Apr 09 15:51:26 CST 2019
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table crm_user
	 * @mbg.generated  Tue Apr 09 15:51:26 CST 2019
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table crm_user
	 * @mbg.generated  Tue Apr 09 15:51:26 CST 2019
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table crm_user
	 * @mbg.generated  Tue Apr 09 15:51:26 CST 2019
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table crm_user
	 * @mbg.generated  Tue Apr 09 15:51:26 CST 2019
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table crm_user
	 * @mbg.generated  Tue Apr 09 15:51:26 CST 2019
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andLongIsNull() {
			addCriterion("Id is null");
			return (Criteria) this;
		}

		public Criteria andLongIsNotNull() {
			addCriterion("Id is not null");
			return (Criteria) this;
		}

		public Criteria andLongEqualTo(Integer value) {
			addCriterion("Id =", value, "Long");
			return (Criteria) this;
		}

		public Criteria andLongNotEqualTo(Integer value) {
			addCriterion("Id <>", value, "Long");
			return (Criteria) this;
		}

		public Criteria andLongGreaterThan(Integer value) {
			addCriterion("Id >", value, "Long");
			return (Criteria) this;
		}

		public Criteria andLongGreaterThanOrEqualTo(Integer value) {
			addCriterion("Id >=", value, "Long");
			return (Criteria) this;
		}

		public Criteria andLongLessThan(Integer value) {
			addCriterion("Id <", value, "Long");
			return (Criteria) this;
		}

		public Criteria andLongLessThanOrEqualTo(Integer value) {
			addCriterion("Id <=", value, "Long");
			return (Criteria) this;
		}

		public Criteria andLongIn(List<Integer> values) {
			addCriterion("Id in", values, "Long");
			return (Criteria) this;
		}

		public Criteria andLongNotIn(List<Integer> values) {
			addCriterion("Id not in", values, "Long");
			return (Criteria) this;
		}

		public Criteria andLongBetween(Integer value1, Integer value2) {
			addCriterion("Id between", value1, value2, "Long");
			return (Criteria) this;
		}

		public Criteria andLongNotBetween(Integer value1, Integer value2) {
			addCriterion("Id not between", value1, value2, "Long");
			return (Criteria) this;
		}

		public Criteria andNameIsNull() {
			addCriterion("Name is null");
			return (Criteria) this;
		}

		public Criteria andNameIsNotNull() {
			addCriterion("Name is not null");
			return (Criteria) this;
		}

		public Criteria andNameEqualTo(String value) {
			addCriterion("Name =", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotEqualTo(String value) {
			addCriterion("Name <>", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameGreaterThan(String value) {
			addCriterion("Name >", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameGreaterThanOrEqualTo(String value) {
			addCriterion("Name >=", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameLessThan(String value) {
			addCriterion("Name <", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameLessThanOrEqualTo(String value) {
			addCriterion("Name <=", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameLike(String value) {
			addCriterion("Name like", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotLike(String value) {
			addCriterion("Name not like", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameIn(List<String> values) {
			addCriterion("Name in", values, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotIn(List<String> values) {
			addCriterion("Name not in", values, "name");
			return (Criteria) this;
		}

		public Criteria andNameBetween(String value1, String value2) {
			addCriterion("Name between", value1, value2, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotBetween(String value1, String value2) {
			addCriterion("Name not between", value1, value2, "name");
			return (Criteria) this;
		}

		public Criteria andPwdIsNull() {
			addCriterion("Pwd is null");
			return (Criteria) this;
		}

		public Criteria andPwdIsNotNull() {
			addCriterion("Pwd is not null");
			return (Criteria) this;
		}

		public Criteria andPwdEqualTo(String value) {
			addCriterion("Pwd =", value, "pwd");
			return (Criteria) this;
		}

		public Criteria andPwdNotEqualTo(String value) {
			addCriterion("Pwd <>", value, "pwd");
			return (Criteria) this;
		}

		public Criteria andPwdGreaterThan(String value) {
			addCriterion("Pwd >", value, "pwd");
			return (Criteria) this;
		}

		public Criteria andPwdGreaterThanOrEqualTo(String value) {
			addCriterion("Pwd >=", value, "pwd");
			return (Criteria) this;
		}

		public Criteria andPwdLessThan(String value) {
			addCriterion("Pwd <", value, "pwd");
			return (Criteria) this;
		}

		public Criteria andPwdLessThanOrEqualTo(String value) {
			addCriterion("Pwd <=", value, "pwd");
			return (Criteria) this;
		}

		public Criteria andPwdLike(String value) {
			addCriterion("Pwd like", value, "pwd");
			return (Criteria) this;
		}

		public Criteria andPwdNotLike(String value) {
			addCriterion("Pwd not like", value, "pwd");
			return (Criteria) this;
		}

		public Criteria andPwdIn(List<String> values) {
			addCriterion("Pwd in", values, "pwd");
			return (Criteria) this;
		}

		public Criteria andPwdNotIn(List<String> values) {
			addCriterion("Pwd not in", values, "pwd");
			return (Criteria) this;
		}

		public Criteria andPwdBetween(String value1, String value2) {
			addCriterion("Pwd between", value1, value2, "pwd");
			return (Criteria) this;
		}

		public Criteria andPwdNotBetween(String value1, String value2) {
			addCriterion("Pwd not between", value1, value2, "pwd");
			return (Criteria) this;
		}

		public Criteria andRoleIsNull() {
			addCriterion("Role is null");
			return (Criteria) this;
		}

		public Criteria andRoleIsNotNull() {
			addCriterion("Role is not null");
			return (Criteria) this;
		}

		public Criteria andRoleEqualTo(Integer value) {
			addCriterion("Role =", value, "role");
			return (Criteria) this;
		}

		public Criteria andRoleNotEqualTo(Integer value) {
			addCriterion("Role <>", value, "role");
			return (Criteria) this;
		}

		public Criteria andRoleGreaterThan(Integer value) {
			addCriterion("Role >", value, "role");
			return (Criteria) this;
		}

		public Criteria andRoleGreaterThanOrEqualTo(Integer value) {
			addCriterion("Role >=", value, "role");
			return (Criteria) this;
		}

		public Criteria andRoleLessThan(Integer value) {
			addCriterion("Role <", value, "role");
			return (Criteria) this;
		}

		public Criteria andRoleLessThanOrEqualTo(Integer value) {
			addCriterion("Role <=", value, "role");
			return (Criteria) this;
		}

		public Criteria andRoleIn(List<Integer> values) {
			addCriterion("Role in", values, "role");
			return (Criteria) this;
		}

		public Criteria andRoleNotIn(List<Integer> values) {
			addCriterion("Role not in", values, "role");
			return (Criteria) this;
		}

		public Criteria andRoleBetween(Integer value1, Integer value2) {
			addCriterion("Role between", value1, value2, "role");
			return (Criteria) this;
		}

		public Criteria andRoleNotBetween(Integer value1, Integer value2) {
			addCriterion("Role not between", value1, value2, "role");
			return (Criteria) this;
		}

		public Criteria andMobileIsNull() {
			addCriterion("Mobile is null");
			return (Criteria) this;
		}

		public Criteria andMobileIsNotNull() {
			addCriterion("Mobile is not null");
			return (Criteria) this;
		}

		public Criteria andMobileEqualTo(String value) {
			addCriterion("Mobile =", value, "mobile");
			return (Criteria) this;
		}

		public Criteria andMobileNotEqualTo(String value) {
			addCriterion("Mobile <>", value, "mobile");
			return (Criteria) this;
		}

		public Criteria andMobileGreaterThan(String value) {
			addCriterion("Mobile >", value, "mobile");
			return (Criteria) this;
		}

		public Criteria andMobileGreaterThanOrEqualTo(String value) {
			addCriterion("Mobile >=", value, "mobile");
			return (Criteria) this;
		}

		public Criteria andMobileLessThan(String value) {
			addCriterion("Mobile <", value, "mobile");
			return (Criteria) this;
		}

		public Criteria andMobileLessThanOrEqualTo(String value) {
			addCriterion("Mobile <=", value, "mobile");
			return (Criteria) this;
		}

		public Criteria andMobileLike(String value) {
			addCriterion("Mobile like", value, "mobile");
			return (Criteria) this;
		}

		public Criteria andMobileNotLike(String value) {
			addCriterion("Mobile not like", value, "mobile");
			return (Criteria) this;
		}

		public Criteria andMobileIn(List<String> values) {
			addCriterion("Mobile in", values, "mobile");
			return (Criteria) this;
		}

		public Criteria andMobileNotIn(List<String> values) {
			addCriterion("Mobile not in", values, "mobile");
			return (Criteria) this;
		}

		public Criteria andMobileBetween(String value1, String value2) {
			addCriterion("Mobile between", value1, value2, "mobile");
			return (Criteria) this;
		}

		public Criteria andMobileNotBetween(String value1, String value2) {
			addCriterion("Mobile not between", value1, value2, "mobile");
			return (Criteria) this;
		}

		public Criteria andPositionIsNull() {
			addCriterion("position is null");
			return (Criteria) this;
		}

		public Criteria andPositionIsNotNull() {
			addCriterion("position is not null");
			return (Criteria) this;
		}

		public Criteria andPositionEqualTo(String value) {
			addCriterion("position =", value, "position");
			return (Criteria) this;
		}

		public Criteria andPositionNotEqualTo(String value) {
			addCriterion("position <>", value, "position");
			return (Criteria) this;
		}

		public Criteria andPositionGreaterThan(String value) {
			addCriterion("position >", value, "position");
			return (Criteria) this;
		}

		public Criteria andPositionGreaterThanOrEqualTo(String value) {
			addCriterion("position >=", value, "position");
			return (Criteria) this;
		}

		public Criteria andPositionLessThan(String value) {
			addCriterion("position <", value, "position");
			return (Criteria) this;
		}

		public Criteria andPositionLessThanOrEqualTo(String value) {
			addCriterion("position <=", value, "position");
			return (Criteria) this;
		}

		public Criteria andPositionLike(String value) {
			addCriterion("position like", value, "position");
			return (Criteria) this;
		}

		public Criteria andPositionNotLike(String value) {
			addCriterion("position not like", value, "position");
			return (Criteria) this;
		}

		public Criteria andPositionIn(List<String> values) {
			addCriterion("position in", values, "position");
			return (Criteria) this;
		}

		public Criteria andPositionNotIn(List<String> values) {
			addCriterion("position not in", values, "position");
			return (Criteria) this;
		}

		public Criteria andPositionBetween(String value1, String value2) {
			addCriterion("position between", value1, value2, "position");
			return (Criteria) this;
		}

		public Criteria andPositionNotBetween(String value1, String value2) {
			addCriterion("position not between", value1, value2, "position");
			return (Criteria) this;
		}

		public Criteria andStatusIsNull() {
			addCriterion("Status is null");
			return (Criteria) this;
		}

		public Criteria andStatusIsNotNull() {
			addCriterion("Status is not null");
			return (Criteria) this;
		}

		public Criteria andStatusEqualTo(Integer value) {
			addCriterion("Status =", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotEqualTo(Integer value) {
			addCriterion("Status <>", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusGreaterThan(Integer value) {
			addCriterion("Status >", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusGreaterThanOrEqualTo(Integer value) {
			addCriterion("Status >=", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusLessThan(Integer value) {
			addCriterion("Status <", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusLessThanOrEqualTo(Integer value) {
			addCriterion("Status <=", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusIn(List<Integer> values) {
			addCriterion("Status in", values, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotIn(List<Integer> values) {
			addCriterion("Status not in", values, "status");
			return (Criteria) this;
		}

		public Criteria andStatusBetween(Integer value1, Integer value2) {
			addCriterion("Status between", value1, value2, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotBetween(Integer value1, Integer value2) {
			addCriterion("Status not between", value1, value2, "status");
			return (Criteria) this;
		}

		public Criteria andAccountAddrIsNull() {
			addCriterion("Account_addr is null");
			return (Criteria) this;
		}

		public Criteria andAccountAddrIsNotNull() {
			addCriterion("Account_addr is not null");
			return (Criteria) this;
		}

		public Criteria andAccountAddrEqualTo(String value) {
			addCriterion("Account_addr =", value, "accountAddr");
			return (Criteria) this;
		}

		public Criteria andAccountAddrNotEqualTo(String value) {
			addCriterion("Account_addr <>", value, "accountAddr");
			return (Criteria) this;
		}

		public Criteria andAccountAddrGreaterThan(String value) {
			addCriterion("Account_addr >", value, "accountAddr");
			return (Criteria) this;
		}

		public Criteria andAccountAddrGreaterThanOrEqualTo(String value) {
			addCriterion("Account_addr >=", value, "accountAddr");
			return (Criteria) this;
		}

		public Criteria andAccountAddrLessThan(String value) {
			addCriterion("Account_addr <", value, "accountAddr");
			return (Criteria) this;
		}

		public Criteria andAccountAddrLessThanOrEqualTo(String value) {
			addCriterion("Account_addr <=", value, "accountAddr");
			return (Criteria) this;
		}

		public Criteria andAccountAddrLike(String value) {
			addCriterion("Account_addr like", value, "accountAddr");
			return (Criteria) this;
		}

		public Criteria andAccountAddrNotLike(String value) {
			addCriterion("Account_addr not like", value, "accountAddr");
			return (Criteria) this;
		}

		public Criteria andAccountAddrIn(List<String> values) {
			addCriterion("Account_addr in", values, "accountAddr");
			return (Criteria) this;
		}

		public Criteria andAccountAddrNotIn(List<String> values) {
			addCriterion("Account_addr not in", values, "accountAddr");
			return (Criteria) this;
		}

		public Criteria andAccountAddrBetween(String value1, String value2) {
			addCriterion("Account_addr between", value1, value2, "accountAddr");
			return (Criteria) this;
		}

		public Criteria andAccountAddrNotBetween(String value1, String value2) {
			addCriterion("Account_addr not between", value1, value2, "accountAddr");
			return (Criteria) this;
		}

		public Criteria andLastErrTimeIsNull() {
			addCriterion("Last_err_time is null");
			return (Criteria) this;
		}

		public Criteria andLastErrTimeIsNotNull() {
			addCriterion("Last_err_time is not null");
			return (Criteria) this;
		}

		public Criteria andLastErrTimeEqualTo(Date value) {
			addCriterion("Last_err_time =", value, "lastErrTime");
			return (Criteria) this;
		}

		public Criteria andLastErrTimeNotEqualTo(Date value) {
			addCriterion("Last_err_time <>", value, "lastErrTime");
			return (Criteria) this;
		}

		public Criteria andLastErrTimeGreaterThan(Date value) {
			addCriterion("Last_err_time >", value, "lastErrTime");
			return (Criteria) this;
		}

		public Criteria andLastErrTimeGreaterThanOrEqualTo(Date value) {
			addCriterion("Last_err_time >=", value, "lastErrTime");
			return (Criteria) this;
		}

		public Criteria andLastErrTimeLessThan(Date value) {
			addCriterion("Last_err_time <", value, "lastErrTime");
			return (Criteria) this;
		}

		public Criteria andLastErrTimeLessThanOrEqualTo(Date value) {
			addCriterion("Last_err_time <=", value, "lastErrTime");
			return (Criteria) this;
		}

		public Criteria andLastErrTimeIn(List<Date> values) {
			addCriterion("Last_err_time in", values, "lastErrTime");
			return (Criteria) this;
		}

		public Criteria andLastErrTimeNotIn(List<Date> values) {
			addCriterion("Last_err_time not in", values, "lastErrTime");
			return (Criteria) this;
		}

		public Criteria andLastErrTimeBetween(Date value1, Date value2) {
			addCriterion("Last_err_time between", value1, value2, "lastErrTime");
			return (Criteria) this;
		}

		public Criteria andLastErrTimeNotBetween(Date value1, Date value2) {
			addCriterion("Last_err_time not between", value1, value2, "lastErrTime");
			return (Criteria) this;
		}

		public Criteria andErrNumberIsNull() {
			addCriterion("Err_number is null");
			return (Criteria) this;
		}

		public Criteria andErrNumberIsNotNull() {
			addCriterion("Err_number is not null");
			return (Criteria) this;
		}

		public Criteria andErrNumberEqualTo(Integer value) {
			addCriterion("Err_number =", value, "errNumber");
			return (Criteria) this;
		}

		public Criteria andErrNumberNotEqualTo(Integer value) {
			addCriterion("Err_number <>", value, "errNumber");
			return (Criteria) this;
		}

		public Criteria andErrNumberGreaterThan(Integer value) {
			addCriterion("Err_number >", value, "errNumber");
			return (Criteria) this;
		}

		public Criteria andErrNumberGreaterThanOrEqualTo(Integer value) {
			addCriterion("Err_number >=", value, "errNumber");
			return (Criteria) this;
		}

		public Criteria andErrNumberLessThan(Integer value) {
			addCriterion("Err_number <", value, "errNumber");
			return (Criteria) this;
		}

		public Criteria andErrNumberLessThanOrEqualTo(Integer value) {
			addCriterion("Err_number <=", value, "errNumber");
			return (Criteria) this;
		}

		public Criteria andErrNumberIn(List<Integer> values) {
			addCriterion("Err_number in", values, "errNumber");
			return (Criteria) this;
		}

		public Criteria andErrNumberNotIn(List<Integer> values) {
			addCriterion("Err_number not in", values, "errNumber");
			return (Criteria) this;
		}

		public Criteria andErrNumberBetween(Integer value1, Integer value2) {
			addCriterion("Err_number between", value1, value2, "errNumber");
			return (Criteria) this;
		}

		public Criteria andErrNumberNotBetween(Integer value1, Integer value2) {
			addCriterion("Err_number not between", value1, value2, "errNumber");
			return (Criteria) this;
		}

		public Criteria andEmailIsNull() {
			addCriterion("Email is null");
			return (Criteria) this;
		}

		public Criteria andEmailIsNotNull() {
			addCriterion("Email is not null");
			return (Criteria) this;
		}

		public Criteria andEmailEqualTo(String value) {
			addCriterion("Email =", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailNotEqualTo(String value) {
			addCriterion("Email <>", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailGreaterThan(String value) {
			addCriterion("Email >", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailGreaterThanOrEqualTo(String value) {
			addCriterion("Email >=", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailLessThan(String value) {
			addCriterion("Email <", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailLessThanOrEqualTo(String value) {
			addCriterion("Email <=", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailLike(String value) {
			addCriterion("Email like", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailNotLike(String value) {
			addCriterion("Email not like", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailIn(List<String> values) {
			addCriterion("Email in", values, "email");
			return (Criteria) this;
		}

		public Criteria andEmailNotIn(List<String> values) {
			addCriterion("Email not in", values, "email");
			return (Criteria) this;
		}

		public Criteria andEmailBetween(String value1, String value2) {
			addCriterion("Email between", value1, value2, "email");
			return (Criteria) this;
		}

		public Criteria andEmailNotBetween(String value1, String value2) {
			addCriterion("Email not between", value1, value2, "email");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table crm_user
	 * @mbg.generated  Tue Apr 09 15:51:26 CST 2019
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table crm_user
     *
     * @mbg.generated do_not_delete_during_merge Tue Apr 09 15:18:44 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}