package com.administration.subject.pojo;

public class RoleMgmt {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_mgmt.Id
     *
     * @mbg.generated Tue Apr 09 15:51:26 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_mgmt.Name
     *
     * @mbg.generated Tue Apr 09 15:51:26 CST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_mgmt.Role_name
     *
     * @mbg.generated Tue Apr 09 15:51:26 CST 2019
     */
    private String roleName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_mgmt.Content
     *
     * @mbg.generated Tue Apr 09 15:51:26 CST 2019
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_mgmt.Status
     *
     * @mbg.generated Tue Apr 09 15:51:26 CST 2019
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_mgmt.Role_Id
     *
     * @mbg.generated Tue Apr 09 15:51:26 CST 2019
     */
    private Integer roleId;
    
    
    

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_mgmt.Id
     *
     * @return the value of role_mgmt.Id
     *
     * @mbg.generated Tue Apr 09 15:51:26 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_mgmt.Id
     *
     * @param Long the value for role_mgmt.Id
     *
     * @mbg.generated Tue Apr 09 15:51:26 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_mgmt.Name
     *
     * @return the value of role_mgmt.Name
     *
     * @mbg.generated Tue Apr 09 15:51:26 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_mgmt.Name
     *
     * @param name the value for role_mgmt.Name
     *
     * @mbg.generated Tue Apr 09 15:51:26 CST 2019
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_mgmt.Role_name
     *
     * @return the value of role_mgmt.Role_name
     *
     * @mbg.generated Tue Apr 09 15:51:26 CST 2019
     */
    public String getRoleName() {
        return roleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_mgmt.Role_name
     *
     * @param roleName the value for role_mgmt.Role_name
     *
     * @mbg.generated Tue Apr 09 15:51:26 CST 2019
     */
    public void setRoleName(String roleName) {
        this.roleName = roleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_mgmt.Content
     *
     * @return the value of role_mgmt.Content
     *
     * @mbg.generated Tue Apr 09 15:51:26 CST 2019
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_mgmt.Content
     *
     * @param content the value for role_mgmt.Content
     *
     * @mbg.generated Tue Apr 09 15:51:26 CST 2019
     */
    public void setContent(String content) {
        this.content = content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_mgmt.Status
     *
     * @return the value of role_mgmt.Status
     *
     * @mbg.generated Tue Apr 09 15:51:26 CST 2019
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_mgmt.Status
     *
     * @param status the value for role_mgmt.Status
     *
     * @mbg.generated Tue Apr 09 15:51:26 CST 2019
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_mgmt.Role_Id
     *
     * @return the value of role_mgmt.Role_Id
     *
     * @mbg.generated Tue Apr 09 15:51:26 CST 2019
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_mgmt.Role_Id
     *
     * @param roleId the value for role_mgmt.Role_Id
     *
     * @mbg.generated Tue Apr 09 15:51:26 CST 2019
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }
}