package com.administration.apply.pojo;

import java.util.Date;

public class AccountMarketingEmail {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_marketing_email.id
     *
     * @mbg.generated Fri Apr 12 11:42:52 CST 2019
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_marketing_email.account_id
     *
     * @mbg.generated Fri Apr 12 11:42:52 CST 2019
     */
    private Long accountId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_marketing_email.strategy_email
     *
     * @mbg.generated Fri Apr 12 11:42:52 CST 2019
     */
    private Byte strategyEmail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_marketing_email.strategy_sms
     *
     * @mbg.generated Fri Apr 12 11:42:52 CST 2019
     */
    private Byte strategySms;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_marketing_email.service_email
     *
     * @mbg.generated Fri Apr 12 11:42:52 CST 2019
     */
    private Byte serviceEmail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_marketing_email.service_sms
     *
     * @mbg.generated Fri Apr 12 11:42:52 CST 2019
     */
    private Byte serviceSms;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_marketing_email.briefing_email
     *
     * @mbg.generated Fri Apr 12 11:42:52 CST 2019
     */
    private Byte briefingEmail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_marketing_email.briefing_sms
     *
     * @mbg.generated Fri Apr 12 11:42:52 CST 2019
     */
    private Byte briefingSms;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_marketing_email.report_valid
     *
     * @mbg.generated Fri Apr 12 11:42:52 CST 2019
     */
    private Byte reportValid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_marketing_email.calendar_email
     *
     * @mbg.generated Fri Apr 12 11:42:52 CST 2019
     */
    private Byte calendarEmail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_marketing_email.subscribe_valid
     *
     * @mbg.generated Fri Apr 12 11:42:52 CST 2019
     */
    private Byte subscribeValid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_marketing_email.add_time
     *
     * @mbg.generated Fri Apr 12 11:42:52 CST 2019
     */
    private Date addTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_marketing_email.update_time
     *
     * @mbg.generated Fri Apr 12 11:42:52 CST 2019
     */
    private Date updateTime;
    
    
    private String name;
    
    private String login;
    
    private String total;

    public String getTotal() {
		return total;
	}

	public void setTotal(String total) {
		this.total = total;
	}

    public String getLogin() {
		return login;
	}

	public void setLogin(String login) {
		this.login = login;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_marketing_email.id
     *
     * @return the value of account_marketing_email.id
     *
     * @mbg.generated Fri Apr 12 11:42:52 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_marketing_email.id
     *
     * @param id the value for account_marketing_email.id
     *
     * @mbg.generated Fri Apr 12 11:42:52 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_marketing_email.account_id
     *
     * @return the value of account_marketing_email.account_id
     *
     * @mbg.generated Fri Apr 12 11:42:52 CST 2019
     */
    public Long getAccountId() {
        return accountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_marketing_email.account_id
     *
     * @param accountId the value for account_marketing_email.account_id
     *
     * @mbg.generated Fri Apr 12 11:42:52 CST 2019
     */
    public void setAccountId(Long accountId) {
        this.accountId = accountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_marketing_email.strategy_email
     *
     * @return the value of account_marketing_email.strategy_email
     *
     * @mbg.generated Fri Apr 12 11:42:52 CST 2019
     */
    public Byte getStrategyEmail() {
        return strategyEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_marketing_email.strategy_email
     *
     * @param strategyEmail the value for account_marketing_email.strategy_email
     *
     * @mbg.generated Fri Apr 12 11:42:52 CST 2019
     */
    public void setStrategyEmail(Byte strategyEmail) {
        this.strategyEmail = strategyEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_marketing_email.strategy_sms
     *
     * @return the value of account_marketing_email.strategy_sms
     *
     * @mbg.generated Fri Apr 12 11:42:52 CST 2019
     */
    public Byte getStrategySms() {
        return strategySms;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_marketing_email.strategy_sms
     *
     * @param strategySms the value for account_marketing_email.strategy_sms
     *
     * @mbg.generated Fri Apr 12 11:42:52 CST 2019
     */
    public void setStrategySms(Byte strategySms) {
        this.strategySms = strategySms;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_marketing_email.service_email
     *
     * @return the value of account_marketing_email.service_email
     *
     * @mbg.generated Fri Apr 12 11:42:52 CST 2019
     */
    public Byte getServiceEmail() {
        return serviceEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_marketing_email.service_email
     *
     * @param serviceEmail the value for account_marketing_email.service_email
     *
     * @mbg.generated Fri Apr 12 11:42:52 CST 2019
     */
    public void setServiceEmail(Byte serviceEmail) {
        this.serviceEmail = serviceEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_marketing_email.service_sms
     *
     * @return the value of account_marketing_email.service_sms
     *
     * @mbg.generated Fri Apr 12 11:42:52 CST 2019
     */
    public Byte getServiceSms() {
        return serviceSms;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_marketing_email.service_sms
     *
     * @param serviceSms the value for account_marketing_email.service_sms
     *
     * @mbg.generated Fri Apr 12 11:42:52 CST 2019
     */
    public void setServiceSms(Byte serviceSms) {
        this.serviceSms = serviceSms;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_marketing_email.briefing_email
     *
     * @return the value of account_marketing_email.briefing_email
     *
     * @mbg.generated Fri Apr 12 11:42:52 CST 2019
     */
    public Byte getBriefingEmail() {
        return briefingEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_marketing_email.briefing_email
     *
     * @param briefingEmail the value for account_marketing_email.briefing_email
     *
     * @mbg.generated Fri Apr 12 11:42:52 CST 2019
     */
    public void setBriefingEmail(Byte briefingEmail) {
        this.briefingEmail = briefingEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_marketing_email.briefing_sms
     *
     * @return the value of account_marketing_email.briefing_sms
     *
     * @mbg.generated Fri Apr 12 11:42:52 CST 2019
     */
    public Byte getBriefingSms() {
        return briefingSms;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_marketing_email.briefing_sms
     *
     * @param briefingSms the value for account_marketing_email.briefing_sms
     *
     * @mbg.generated Fri Apr 12 11:42:52 CST 2019
     */
    public void setBriefingSms(Byte briefingSms) {
        this.briefingSms = briefingSms;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_marketing_email.report_valid
     *
     * @return the value of account_marketing_email.report_valid
     *
     * @mbg.generated Fri Apr 12 11:42:52 CST 2019
     */
    public Byte getReportValid() {
        return reportValid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_marketing_email.report_valid
     *
     * @param reportValid the value for account_marketing_email.report_valid
     *
     * @mbg.generated Fri Apr 12 11:42:52 CST 2019
     */
    public void setReportValid(Byte reportValid) {
        this.reportValid = reportValid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_marketing_email.calendar_email
     *
     * @return the value of account_marketing_email.calendar_email
     *
     * @mbg.generated Fri Apr 12 11:42:52 CST 2019
     */
    public Byte getCalendarEmail() {
        return calendarEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_marketing_email.calendar_email
     *
     * @param calendarEmail the value for account_marketing_email.calendar_email
     *
     * @mbg.generated Fri Apr 12 11:42:52 CST 2019
     */
    public void setCalendarEmail(Byte calendarEmail) {
        this.calendarEmail = calendarEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_marketing_email.subscribe_valid
     *
     * @return the value of account_marketing_email.subscribe_valid
     *
     * @mbg.generated Fri Apr 12 11:42:52 CST 2019
     */
    public Byte getSubscribeValid() {
        return subscribeValid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_marketing_email.subscribe_valid
     *
     * @param subscribeValid the value for account_marketing_email.subscribe_valid
     *
     * @mbg.generated Fri Apr 12 11:42:52 CST 2019
     */
    public void setSubscribeValid(Byte subscribeValid) {
        this.subscribeValid = subscribeValid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_marketing_email.add_time
     *
     * @return the value of account_marketing_email.add_time
     *
     * @mbg.generated Fri Apr 12 11:42:52 CST 2019
     */
    public Date getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_marketing_email.add_time
     *
     * @param addTime the value for account_marketing_email.add_time
     *
     * @mbg.generated Fri Apr 12 11:42:52 CST 2019
     */
    public void setAddTime(Date addTime) {
        this.addTime = addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_marketing_email.update_time
     *
     * @return the value of account_marketing_email.update_time
     *
     * @mbg.generated Fri Apr 12 11:42:52 CST 2019
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_marketing_email.update_time
     *
     * @param updateTime the value for account_marketing_email.update_time
     *
     * @mbg.generated Fri Apr 12 11:42:52 CST 2019
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}